#!/bin/bash

if [ "${DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -d /tmp/in_target.d/rpms/ ]; then
    rpmfiles=($(find /tmp/in_target.d/rpms -name "*.rpm"))
    if [ ${#rpmfiles[*]} -gt 0 ]; then
        rpm -ivh  /tmp/in_target.d/rpms/*.rpm
    fi
fi
