#!/bin/bash

if [ ${DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail
set -x

function gen_fstab () {
    echo "gen fstab"
    echo "root fs uuid : $ROOT_FS_UUID"
    echo "UUID=$ROOT_FS_UUID    /    ext4    defaults  0 0"  >>  /etc/fstab
    echo "UUID=${BOOT_UUID} /boot vfat defaults 0 0" >> /etc/fstab
}

gen_fstab
