#!/bin/bash

if [ ${DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail
set -x

function set_rootpwd () {
    str=`sed -n '/^root:/p' /etc/shadow | awk -F "root:" '{print $2}'`
    mv /etc/shadow /etc/shadow_bak
    sed -i '/^root:/d' /etc/shadow_bak
    echo "root:"${ROOT_PWD}${str:1} > /etc/shadow
    cat /etc/shadow_bak >> /etc/shadow
    rm -rf /etc/shadow_bak
    chmod 000 /etc/shadow
}

set_rootpwd
