#!/bin/bash

if [ ${DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Abort early if dib-run-parts is not found to prevent a meaningless
# error message from the subsequent install command
DIB_RUN_PARTS=$SCRIPT_HOME/dib-run-parts

sudo install -m 0755 -o root -g root -D \
    $DIB_RUN_PARTS \
    $TARGET_ROOT/usr/local/bin/dib-run-parts
